#!/bin/bash

# certbot cron helper.
# By: Wesley Robbins
# Description: Certbot helper enables you to run the renew 
#   script daily and tests if within 5 days of expiration.  If 
#   so will auto renew. Works for apache andcan be modified to
#   work with any web client. 
#
# Usage: Edit certbot-cron and change URL and CERTBOTLOC. Set PrintInfo to 'no' if you do not want daily reports.  Edit crontab as root.   
#  crontab -e
#  0 3 0 * * path-to-certbot-cron 2>&1  

URL='wezzel.com'
PrintInfo='no'
CERTBOTLOC=/home/wez/certs/certbot-auto
WEBSTART='/etc/init.d/apache2 start'
WEBSTOP='/etc/init.d/apache2 stop'

notBefore=`echo | /usr/bin/openssl s_client -connect ${URL}:443 2>/dev/null | openssl x509 -noout -dates | grep notBefore | cut -d'=' -f2`
notAfter=`echo | /usr/bin/openssl s_client -connect ${URL}:443 2>/dev/null | openssl x509 -noout -dates | grep notAfter | cut -d'=' -f2`

notBeforeUnix=`date --date="${notBefore}" +"%s"`
today=`date`
todayUnix=`date --date="${today}" +"%s"`
eightyfivedays="7344000"
renewDateUnix=$((notBeforeUnix + eightyfivedays))
renewDate=`date -d @$renewDateUnix`


if [ $renewDateUnix -gt $todayUnix  ]; then
  if [ ${PrintInfo} = "yes" ]; then
    echo "------------------"
    echo "You still have time. Today is ${today}. Waiting until ${renewDate} to renew. ${notAfter} is when your SSL cert expires. "
    echo "------------------"
  fi
else

  if [ ${PrintInfo} = 'yes'  ]; then
    echo "\n\n"
    echo "Time to renew your cert. Today is ${today} and your cert expires ${notAfter}"
  fi
    ${WEBSTOP}
    #${CERTBOTLOC} renew --dry-run
    ${CERTBOT} renew --quiet --no-self-upgrade
    ${WEBSTART}
fi
